version: 2.1

jobs:
  test-docker-mirror:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      
      - setup_remote_docker      
      - run:
          name: Check Docker info BEFORE mirror setup
          command: |
            echo "===== BEFORE MIRROR SETUP ====="
            docker system info | grep -A 5 "Registry" || echo "No registry mirrors configured"
      
      - run:
          name: Configure Docker registry mirror
          command: |
            echo "Writing daemon.json..."
            cat \<< EOF | ssh remote-docker "sudo tee /etc/docker/daemon.json"
            {
              "registry-mirrors": ["https://mirror.gcr.io"],
              "log-level": "debug"
            }
            EOF
            
            echo "Reloading Docker daemon config..."
            ssh remote-docker "sudo pkill -SIGHUP dockerd"
            
            echo "Waiting for reload to complete..."
            sleep 2
      
      - run:
          name: Verify Docker info AFTER mirror setup
          command: |
            echo "===== AFTER MIRROR SETUP ====="
            docker system info | grep -A 5 "Registry"
            
            # Check specifically for the mirror
            if docker system info | grep -q "https://mirror.gcr.io"; then
              echo "✅ SUCCESS: Registry mirror is configured!"
            else
              echo "❌ FAILED: Registry mirror NOT found"
              exit 1
            fi
      
      - run:
          name: Test pulling an image (should use mirror)
          command: |
            # Clear any existing nginx images
            docker rmi nginx:alpine 2>/dev/null || true
            
            # Pull the image
            echo "Pulling nginx:alpine..."
            docker pull nginx:alpine
            
            # Check daemon logs for mirror usage
            echo "===== Checking Docker daemon logs ====="
            ssh remote-docker "sudo journalctl -u docker -n 50 --no-pager" | grep -i mirror || echo "No mirror mentioned in logs"
            ssh remote-docker "sudo journalctl -u docker -n 100 --no-pager" | grep -E "(mirror\.gcr\.io|Pulling)" || echo "No mirror activity found"
            ssh remote-docker "sudo journalctl -u docker --since '1 minute ago' --no-pager" | grep -i "mirror.gcr.io\|registry" 


            echo "Image pulled successfully!"
            docker images | grep nginx
      
      - run:
          name: Verify daemon.json persists
          command: |
            echo "Checking daemon.json still exists..."
            ssh remote-docker "cat /etc/docker/daemon.json"

workflows:
  test-mirror:
    jobs:
      - test-docker-mirror
